import * as Vue from "vue";
import App from "./App.vue";
import router from "./router";
import i18n from "./i18n";
import PrimeVue from "primevue/config";
import DataView from "primevue/dataview";
import Dropdown from "primevue/dropdown";
import DataViewLayoutOptions from "primevue/dataviewlayoutoptions";
import Card from "primevue/card";
import Button from "primevue/button";
import InputText from "primevue/inputtext";
import Menubar from "primevue/menubar";
import Sidebar from "primevue/sidebar";
import Carousel from "primevue/carousel";
import "primevue/resources/themes/saga-orange/theme.css";
import "primevue/resources/primevue.min.css";
import "primeicons/primeicons.css";
import "primevue/resources/themes/md-light-indigo/theme.css";
import "primeflex/primeflex.css";

const app = Vue.createApp(App);
app.use(i18n);
app.use(router);
app.use(PrimeVue);
app.component("DataView", DataView);
app.component("DropdownComponent", Dropdown);
app.component("DataViewLayoutOptions", DataViewLayoutOptions);
app.component("CardComponent", Card);
app.component("ButtonComponent", Button);
app.component("InputText", InputText);
app.component("MenubarComponent", Menubar);
app.component("SidebarComponent", Sidebar);
app.component("CarouselComponent", Carousel);
app.component("DropdownComponent", Dropdown);
app.mount("#app");
